def Task1():
    print("======================================")
    print("Name of College:")
    print("======================================")
    print("choose your option")
    print("Add New Student")
    print("Delete Student")
    print("Search Student")
def Task2():
    print("========================================")
    print("Add New Student")
    print("========================================")
    name=input("Enter Name:")
    age=input("Enter Age:")
    phoneNumber=input("Enter PhoneNumber:")
    print("New Student is Added")
def Task3():
    print("=========================================")
    print("Delete Student")
    print("=========================================")
    name=input("Enter Name of Student:")
    print("Student is deleted")
def Task4():
    print("=========================================")
    print("Search Student")
    print("=========================================")
    name=input("Enter Name of Student:")
    print("Name:",name)
Task1()
Task2()
Task3()
Task4()
