def choose():
    print("======================================")
    print("Name of College:")
    print("======================================")
    print("choose your option")
    print("Add New Student")
    print("Delete Student")
    print("Search Student")
def Add():
    print("========================================")
    print("Add New Student")
    print("========================================")
    name=input("Enter Name:")
    age=input("Enter Age:")
    phoneNumber=input("Enter PhoneNumber:")
    print("New Student is Added")
def Delete():
    print("=========================================")
    print("Delete Student")
    print("=========================================")
    name=input("Enter Name of Student:")
    print("Student is deleted")
def Search():
    print("=========================================")
    print("Search Student")
    print("=========================================")
    name=input("Enter Name of Student:")
    print("Name:",name)
choose()
Add()
Delete()
Search()
